const images = {
  envelope: require('./icons/envelope.png'),
  padlock: require('./icons/padlock.png'),
  logo: require('./icons/logo.png'),
  checkbox: require('./icons/checkbox_on_light.png'),
  placeholder: require('./icons/placeholder.png'),
  user: require('./icons/user.png'),
  zipcode: require('./icons/zip-code.png'),
  parking: require('./icons/parking.png'),
  license: require('./icons/license.png'),
  radio_on: require('./icons/radio_on.png'),
  radio_off: require('./icons/radio_off.png'),
  backIcon: require('./icons/backIcon.png'),
  forgetIcon: require('./icons/forgetIcon.png'),
  resetIcon: require('./icons/resetIcon.png'),
  facebook: require('./icons/facebook.png'),
  uncheck_checkbox: require('./icons/uncheck_checkbox.png'),
  backIconBlue: require('./icons/backIconBlue.png'),
  verifyOtpIcon: require('./icons/verifyOtpIcon.png'),
  location: require('./icons/location.png'),
  menu_icon: require('./icons/menu_icon.png'),
  notification: require('./icons/notification.png'),
  notification_white: require('./icons/notification_white.png'),
  search: require('./icons/search.png'),
  logout: require('./icons/logout.png'),
  logout_white: require('./icons/logout_white.png'),
  dummy_user: require('./icons/dummy_user.png'),
  menu_bg: require('./icons/menu_bg.png'),

  group: require('./icons/group.png'),
  credit_card: require('./icons/credit-card.png'),
  menu_user: require('./icons/menu_user.png'),
  change_password: require('./icons/change_password.png'),
  note: require('./icons/note.png'),
  dummy_photo: require('./icons/dummy_photo.png'),
  home: require('./icons/ic_home.png'),
  time: require('./icons/time.png'),
  uploadcloud: require('./icons/upload-to-cloud.png'),
  star: require('./icons/star.png'),
  icondirection: require('./icons/icon-direction.png'),
  iconcar: require('./icons/icon-car.png'),
  valentbg: require('./icons/valent-bg.png'),
  edit: require('./icons/ic_edit.png'),
};

export default images;
