const images = {
  backArrow: require('../assets/images/arrow/back.png'),
  whiteBackArrow: require('../assets/images/arrow/whiteBackArrow.png'),
  check: require('../assets/images/check/check.png'),
  uncheck: require('../assets/images/check/uncheck.png'),
  google: require('../assets/images/googleIcon/google.png'),
  facebook: require('../assets/images/facebookIcon/facebook.png'),
  rightArrowGray: require('../assets/images/arrow/arrowRight_gray.png'),
  leftArrowGray: require('../assets/images/arrow/backArrow1.png'),
  visaIcon: require('../assets/images/payIcon/visaIcon.png'),
  paypalIcon: require('../assets/images/payIcon/paypalIcon.png'),
  applePayIcon: require('../assets/images/payIcon/applePayIcon.png'),
  payIcon: require('../assets/images/payIcon/payIcon.png'),
  arrowRightBlue: require('../assets/images/arrow/arrowRightBlue1.png'),
  checkIconWhite: require('../assets/images/check/checkIconWhite.png'),
  downloadWhite: require('../assets/images/check/downloadWhite.png'),
  listen: require('../assets/images/demo/listen.png'),
  compare: require('../assets/images/demo/compare.png'),
  imagine: require('../assets/images/demo/imagine.png'),
  repeat: require('../assets/images/demo/repeat.png'),
  arrowUp: require('../assets/images/arrow/arrowUp.png'),
  circle: require('../assets/images/arrow/circle.png'),
  radioButtonOn: require('../assets/images/radioButtonOn/radioButtonOn.png'),
  radioButtonOff: require('../assets/images/radioButtonOff/radioButtonOffCopy.png'),
  radioButtonOn_blue: require('../assets/images/radioButtonOn_blue/radioButtonOn.png'),
  radioButtonOff_blue: require('../assets/images/radioButtonOff_blue/radioButtonOff.png'),
  playButton: require('../assets/images/playButton/playButton.png'),
  pauseButton: require('../assets/images/pauseButton/pauseButton.png'),
  refreshButton: require('../assets/images/refreshButton/refreshButton.png'),
  playIcon: require('../assets/images/playButtonBlack.png'),
  refreshIcon: require('../assets/images/refreshIcon/refreshIcon.png'),
  pauseIcon: require('../assets/images/pauseIcon/icon-pause.png'),
  iconSpeak: require('../assets/images/iconSpeak/iconSpeak.png'),
  gpay: require('../assets/images/googlePay/gpay.png'),
  appLogo: require('../assets/images/appLogo/group11.png'),
  closeIcon: require('../assets/images/arrow/close_icon/close3x.png'),
  lock: require('../assets/images/lock/unlock.png'),
  overView: require('../assets/images/over_view/grid.png'),
  download: require('../assets/images/download/download.png'),
  settings: require('../assets/images/settings/settings.png'),
  ringLoader: require('../assets/images/app_loader.gif'),
  headphones: require('../assets/images/headphones/headphones.png'),
  iconTopCompare: require('../assets/images/iconTopCompare/iconTopCompare.png'),
  eye: require('../assets/images/eye/eye.png'),
  imaginationImg: require('../assets/images/iconTopImageSituationBlack.png'),
  iconListen: require('../assets/images/iconTopListenBlack.png'),
  iconRepeat: require('../assets/images/iconTopRepeatBlack.png'),
  speakIcon: require('../assets/images/iconTopSpeakBlack.png'),
  messageIcon: require('../assets/images/messageSquare/messageSquare.png'),
  buttonPlay: require('../assets/images/playButton_/playButton.png'),
  repeatButton: require('../assets/images/repeatButton/repeat10Button.png'),
  rotate: require('../assets/images/rotate/rotateCw.png'),
  bitmap: require('../assets/images/lessonImg/bitmap.png'),
  fingerSwipe: require('../assets/images/fingerSwipeIcon/finger.png'),
  trashImage: require('../assets/images/delete/delete(6).png'),
  downloadImg: require('../assets/images/downloadImg/download.png'),
  whiteBackArrow: require('../assets/img/back.png'),
  menuImg: require('../assets/img/menu.png'),
  close: require('../assets/images/x.png'),
  left_Icon: require('../assets/images/left_Icon.png'),
  right_Icon: require('../assets/images/right_Icon.png'),
  edit_icon: require('./../assets/images/edit.png'),
  round_icon: require('./../assets/images/Round.png'),
  info:require('./../assets/images/info.png'),
  // appLoader: require('../assets/images/appLoader.svg'),
};

export default images;
